apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: user-svc
  name: user-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      service: user-svc
  template:
    metadata:
      labels:
        service: user-svc
    spec:
      containers:
        - image: uncledrewbie/udagram-user-svc
          name: user-svc
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: user-svc-env-config
          env:
            - name: UDAGRAM_DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: udagram-db-secret
            - name: UDAGRAM_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: udagram-db-secret
            - name: UDAGRAM_JWT_KEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: udagram-jwt-secret
          ports:
            - containerPort: 8080
      restartPolicy: Always
